### ISSUE TITLE
Multiple Data Filters

### ISSUE THREAD

**Issue by migvidal5** [Teamworksapp/smartabaseR#10]
I am unable to pull data that has multiple data filters like the code referenced below. This is something that could be done in the neon package.

The error I get with the below code is "Error in `sb_get_event_filter()`:
! `data_condition` must be one of "equal_to", "not_equal_to", "contains", "less_than", "greater_than", "less_than_or_equal_to", or "greater_than_or_equal_to", not
  "not_equal_to"."

```r
df4 <- sb_get_event(
  form = "Oura Readiness and Sleep Summary",
  date_range = sb_date_range("4", "weeks"),
  url = "ussoccer.smartabase.com/ams",
  username = "username",
  password = "password",
  filter = sb_get_event_filter(
    data_key = c("Resting HR Flag", "Sleep Time"),
    data_value = c("No Flag", "7"),
    data_condition = c("not_equal_to", "less_than")
  )
)
```

**Comment by zacpross** [comment]
Thanks @migvidal5, confirmed on my end. Looks like this is `rlang::arg_match()` not being able to deal with multiple values. I'll have a fix up soon

**Comment by zacpross** [comment]
@migvidal5 v0.0.9 up now with a fix re: multiple filters, please let me know if you're still having any issues though 🙏🏻

**Comment by zacpross** [comment]
@migvidal5 Good to hear it's resolved now. In terms of your question, unfortunately no, data filters in Smartabase are connected by AND logic (talked about towards the end of this [section](https://teamworksapp.github.io/smartabaseR/articles/exporting-data.html#data-filtering)). So you can see how it's impossible to filter for a record that has a drill title that is simultaneously equal to both "ENTIRE SESSION" and "GAME-FIRST HALF", for instance.

Using OR logic in our data filters is definitely something the team is working on though for future API data extraction endpoints.
